### ISSUE TITLE
Flux v0.13.13 gpu crashes

### ISSUE THREAD

**Issue by potaslab** [FluxML/Flux.jl#2199] opened 2023-03-04 05:30 UTC
After moving to v0.13.13 from v0.12.8 there appears to be some problem with transferring flux models to the gpu. I now get this error message:

```
Could not locate cudnn_ops_infer64_8.ddl. Please make sure it is in your library path!
```

This resulted in Julia to terminate completely (in VS Code). 

The upgrade from 12.8 to 13.13 was not straight forward, I had to completely remove Flux.jl first, then add it (there were dependency issues stopping it otherwise). That process may have altered the CUDA version (im running CUDA v4.0.1), but I don't have a record of what I did, but I did remove other dependent packages, in the hope the correct ones would be reinstalled automatically.  

The motivation to upgrade to 0.13.13 was to update my flux models with MLUtils.flatten layers, so all my other ML projects can run the latest and future versions of Flux. When I pushed the model with either Flux.flatten, or MLUtils.flatten onto the GPU, I got the above error and which killed Julia. I suspect its a CUDA thing, not the updates to the new MLUtils.flatten implementation.  

Right now I can't run the latest version of Flux.

**Comment by potaslab** [comment] 2023-03-04 05:36
It appears that the error is related to some NVIDIA 

If it helps here is the versioninfo() for CUDA.jl on my machine: 

```
julia> CUDA.versioninfo()
CUDA driver 11.7
NVIDIA driver 516.94.0

Libraries:
- CUBLAS: 11.11.3
- CURAND: 10.3.0
- CUFFT: 10.9.0
- CUSOLVER: 11.4.1
- CUSPARSE: 11.7.5
- CUPTI: 18.0.0
- NVML: 11.0.0+516.94

Toolchain:
- Julia: 1.8.5
- LLVM: 13.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

1 device:
  0: NVIDIA GeForce GTX 1080 Ti (sm_61, 9.664 GiB / 11.000 GiB available)
```

**Comment by ToucheSir** [comment] 2023-03-04 06:12
Yes, this is a duplicate of https://github.com/FluxML/Flux.jl/issues/2193 and is being tracked on the CUDA.jl side.

**Closed by ToucheSir** 2023-03-04 06:12 UTC
