### ISSUE TITLE
Creation of Adversarial Examples

### ISSUE THREAD

**Issue by felipewhitaker** [FluxML/Flux.jl#2229] opened 2023-04-14 23:41 UTC
### Motivation and description

I read _Deep neural networks and mixed integer linear optimization_ [[1]] and became curious to implement it using Julia. 

The idea is that, if you have a trained network, you should be capable of slightly modifying its input to create an adversarial example that makes the network fail. 

There are other ways of doing it e.g. FGSM [[2]] [[3]], but the approach of using optimizion is more interesting due to the fact that creating new constraints (e.g. the network must be at least 20% more confident on the wrong prediction) far easier.

With this in mind, the example below is a simple case of how the network creation and optimization model.

```julia
using Flux
using JuMP, Ipopt

mse = (y, yhat) -> sum((y .- yhat) .^ 2) #  define loss function

# generate data
n_features, n_data, n_out = 1, 2, 1
X, y = rand(n_features, n_data), rand(n_out, n_data)

# create example model
clf = Dense(n_features, n_out)

# ... train network

# create the optimization model
model = Model(Ipopt.Optimizer)

@variable(model, noise[1:n_data])
@expression(model, X_noise[i in 1:n_data], X[1, i] + noise[i])

# find noise that maximizes network error
@objective(model, Max, sum((clf(X_noise[i]) - y[i])^2 for i in 1:n_data))
optimize!(model)
```

The error I receive is below:

```julia
julia> @objective(model, Max, sum((clf(X_noise[i]) - y[i])^2 for i in 1:n_data))
ERROR: MethodError: no method matching (::Dense{typeof(identity), Matrix{Float32}, Vector{Float32}})(::AffExpr)
Closest candidates are:
  (::Dense)(::AbstractVecOrMat) at C:\Users\felipe\.julia\packages\Flux\Nzh8J\src\layers\basic.jl:170
  (::Dense)(::AbstractArray) at C:\Users\felipe\.julia\packages\Flux\Nzh8J\src\layers\basic.jl:177
Stacktrace:
 [1] macro expansion
   @ C:\Users\felipe\.julia\packages\MutableArithmetics\geMUn\src\rewrite.jl:322 [inlined]
 [2] macro expansion
   @ C:\Users\felipe\.julia\packages\JuMP\pQApG\src\macros.jl:1501 [inlined]
 [3] top-level scope
   @ c:\Users\felipe\Documents\github\masters\mlopt\presentation\exercise\adversarial.jl:57
```

I understand that it is due the network `clf` not processing the affine expression related to `X_noise[i]`. However, I undertand that, in this simple case, `clf` could be transformed into a function with its parameters to execute the linear regression, as below:

```julia
β_1, β_0 = params(clf)
lm = (β_0, β_1, x) -> β_0 + β_1 * x
```

Modifying the objective to be:

```julia
@objective(model, Max, sum((lm(β_0, β_1, X_noise[i])[1] - y[i])^2 for i in 1:n_data))
```

Which JuMP accepts and optimizes.

Therefore: would it be possible to export a Flux model as a set of weights and rules (similar to the `lm` function), enabling its use in other contexts?

I am using `Julia 1.8.5`. Below are the dependencies for the code above.

```[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
```

[1]: https://link.springer.com/article/10.1007/s10601-018-9285-6
[2]: https://pytorch.org/tutorials/beginner/fgsm_tutorial.html
[3]: https://www.tensorflow.org/tutorials/generative/adversarial_fgsm?hl=fr

Other notes:

- Disconsider that the problem is unbounded as there are no constraints on `noise`
- Disconsider that the network does not use any activation function, making it linear and does creates a linear problem for the optimizer: the focus of this request is to be able to export the model in a way that it doesn't depend on receiveing a number to be executable.

**Comment by CarloLucibello** [comment] 2023-04-17 12:41
In think you should use JUMP's `@NLobjective` and register the `clf` function and is gradient, see JuMP's manual 
](https://jump.dev/JuMP.jl/dev/reference/nlp/#JuMP.@NLobjective)
That said, reading 
https://jump.dev/JuMP.jl/stable/manual/nlp/#User-defined-functions-with-vector-inputs
I suspect that JuMP is not the right tool for solving these typically high-dimensional tasks.
You should explore NLSolve.jl and Optim.jl

I'm closing the issue since it doesn't feel a Flux-related problem, but feel free to re-open if you think it is.

**Closed by CarloLucibello** 2023-04-17 12:41 UTC

**Comment by darsnack** [comment] 2023-04-17 14:19
Keeping aside which packages are the best way to go about your task for creating adversarial examples without AD/ML tooling...

I think there is a concrete Flux-related request here. You want layers to be split into parameters and rules in a way that is "layer type-free" (i.e. something you can pass to another library With `Dense` being hidden). This is a request we have discussed already—creating functional equivalents for all layers. It is being tracked at #2013 so I will leave this closed.

That being said, I don't think this will help your issue. The problem isn't that `Dense` is misunderstood by JuMP, it is that `Dense` was passed an `AffExpr`.
This is caused by the way you defined your objective expression:
```julia
sum((clf(X_noise[i]) - y[i])^2 for i in 1:n_data)
```
Here, `X_noise[i]` is a scalar `AffExpr`. `Dense` only accepts `AbstractArray`s not scalars. This restriction would likely still be in place for the functional version of `Dense`, so it won't solve your problem even if we added the feature.

Passing a scalar to a neural network breaks the underlying assumption for any ML layer framework—that the inputs are arrays. **Note your original code already works with Flux just fine if you use array arithmetic**. Here is the code the worked for me. I've highlighted what I changed.
```julia
using Flux
using JuMP, Ipopt

mse = (y, yhat) -> sum((y .- yhat) .^ 2) #  define loss function

# generate data
n_features, n_data, n_out = 1, 2, 1
X, y = rand(n_features, n_data), rand(n_out, n_data)

# create example model
clf = Dense(n_features, n_out)

# ... train network

# create the optimization model
model = Model(Ipopt.Optimizer)

# NOTE THE CHANGES HERE!!
# Flux wants things in terms of (features x samples)
@variable(model, noise[1:n_features, 1:n_data])
@expression(model, X_noise[1:n_features, i in 1:n_data], X[1, i] + noise[i])

# NOTE THE CHANGES HERE!!
# express things how you would in linear algebra class
# and broadcast over sample dimension
# find noise that maximizes network error
@objective(model, Max, sum((clf(X_noise) .- y).^2))
optimize!(model)
```
