### ISSUE TITLE
Mutating Arrays not Allowed

### ISSUE THREAD

**Issue by smitch151** [FluxML/Flux.jl#1375] opened 2020-10-29 16:03 UTC
Hello, I'm trying to write a program where for each instance of training I draw a new set of data. My NN takes in the set of observations drawn from a normal distribution and then estimates the normal distributions mean and variance. However, when I try to run the code, I get the error "Mutating Arrays not Allowed" when trying to train the NN. Any advice? 

Code is below: 

```

import Pkg; Pkg.add("IterTools")
using Random, Distributions, Flux, Plots
using Flux: @epochs
using IterTools: ncycle

# Setting the seed
Random.seed!(123) 

# Initial Inputs
μ = randn(1,1)[1] #mean
σ = randn(1,1)[1] #variance
σ = σ.^2 .+ 0.01
n_draws = 100 #number of draws 

# Drawing the dataset
ydata = [μ;σ]
NN = Chain(x -> x,
             Dense(n_draws,20,relu),
             Dense(20,20,relu),
             Dense(20,2))

function gen_data(μ,σ)
    xdata = rand(Normal(μ,σ),n_draws)
end 

function loss2(μ,σ) 
    xdata = gen_data(μ,σ)
    pred = NN(xdata)
    totalloss = sum((pred .- ydata).^2)
    return totalloss
end

@show loss2(μ,σ)
ps = Flux.params(NN)
evalcb() = @show(loss2(μ,σ))

### Training

# train model on the same data num_cycle times
num_cycles = 1
data = ncycle([(μ,σ)], num_cycles)

# trainign the model 
opt = ADAM(0.01)
@epochs 100 Flux.train!(loss2, ps, data, opt, cb=evalcb)





```

**Comment by CarloLucibello** [comment] 2020-11-15 15:29
I ran your script but I could not reproduce the error

**Comment by CarloLucibello** [comment] 2020-11-15 15:29
I'm closing this, feel free to reopen if the error persists

**Closed by CarloLucibello** 2020-11-15 15:29 UTC
