### ISSUE TITLE
Support for asymmetric padding

### ISSUE THREAD

**Issue by ayush1999** [FluxML/Flux.jl#258] opened 2018-05-08 07:15 UTC
While loading the GoogleNet ONNX model, I came across a padding of the type `[0,0,2,2]`. Due to its asymmetric nature, it couldn't be implemented in Flux.

As @tejank10 and I were talking, we think its time Flux starts supporting asymmetric padding. It's strange that nobody ever felt a need for this before.

**Comment by jekbradbury** [comment] 2018-05-08 18:26
Some background (see https://github.com/onnx/onnx/issues/401#issuecomment-356281852):

What happens is that nobody ever _wants_ to use asymmetric padding, but sometimes it's impossible to have perfectly symmetric padding (I believe if the input and output sizes aren't either both even or both odd). And different frameworks have historically made different assumptions about _which asymmetry_ to choose when they're asked to pad symmetrically but can't make it perfectly symmetric. So ONNX has to represent these differences explicitly, which means we probably want to figure out what choice Flux/NNlib is implicitly making and also provide a means to bypass that choice and use explicitly provided asymmetries...

**Comment by jekbradbury** [comment] 2018-05-08 18:51
More digging: I think this is where the asymmetry comes from https://github.com/pytorch/pytorch/blob/master/caffe2/onnx/onnx_exporter.cc#L491 and this is what Caffe2 itself does when it sees such an asymmetry https://github.com/pytorch/pytorch/blob/master/caffe2/operators/pool_op_cudnn.cu#L225. If this really does originate from Caffe "legacy padding behavior" (https://github.com/pytorch/pytorch/blob/master/caffe2/proto/caffe2_legacy.proto#L23) then we may still have problems related to the different output size?? I'm not sure...

**Comment by MikeInnes** [comment] 2018-06-26 13:48
Worth figuring out if we can do "nearest symmetric" here, or otherwise convert back to symmetric padding. @ayush1999 perhaps do some digging and figure out what we're doing implicitly here?

If we go for this it'll be quite an invasive change over the convolution stack, though I'm sure we can keep the current API everywhere by default.

**Comment by ayush1999** [comment] 2018-06-26 20:52
Asymmetric padding generally arises when dealing with models made using Caffe. Currently, we specify padding in Flux like `(a,b)`, which is actually expanded to `(a,b,a,b)`. However, padding in Caffe is written as `(a,b,c,d)`. As you mentioned, we can convert asymmetric padding into symmetric padding, as I have been doing in ONNX.jl ([here](https://github.com/FluxML/ONNX.jl/blob/master/src/graph/ops.jl#L28)). However, there are a few shortcomings:

1. It affects the performance of the model, which is fairly obvious.

2. In many cases, asymmetric padding cannot be converted to symmetric padding, without changing the output shape. For example, it isn't possible to convert `(0,0,1,1)` or `(0,0,3,3)` to symmetric padding.

**Comment by ianshmean** [comment] 2019-01-06 18:36
It would be good to re-start this discussion (after it being brought up in the machine-learning slack channel). In addition to the above mentioned GoogleNet issue, this prevents the [tony_yolov2 ONNX models](https://github.com/onnx/models/tree/master/tiny_yolov2) from being usable in flux, resulting in a `12×12×125×1` output rather than the expected `13×13×125×1`

**Comment by lazarusA** [comment] 2019-02-22 16:44
How is this going?, still in progress.... ??

**Comment by bhvieira** [comment] 2019-08-06 14:20
@MikeInnes this works already, right?

**Comment by ianshmean** [comment] 2019-08-06 14:55
According to https://github.com/FluxML/NNlib.jl/pull/84#issuecomment-481126094 it is. 

I believe ONNX still needs some work, but I haven't re-tested the yolov2 ONNX models I mentioned above

**Comment by bhvieira** [comment] 2020-04-16 13:17
@dhairyagandhi96 or @CarloLucibello I think this issue can be safely closed, asymmetric padding has been merged a long time ago

**Comment by dhairyagandhi96** [comment] 2020-04-16 13:25
Thanks!

**Closed** 2020-04-16 13:25 UTC

**Comment by AStupidBear** [comment] 2020-04-22 03:21
But assymetric padding does not work for `CUDNN`.

```
using Flux
x = randn(100, 100, 7, 100) |> gpu;
model = Conv((10,10), 7 => 3, pad = (9, 0, 9, 0)) |>gpu;
model(x)
┌ Warning: CuDNN does not support asymmetric padding; defaulting to symmetric choice
└ @ CuArrays.CUDNN ~/shared/.julia/packages/CuArrays/e8PLr/src/dnn/conv.jl:49
ERROR: CUDNNError: CUDNN_STATUS_BAD_PARAM (code 3)
```

**Comment by AStupidBear** [comment] 2020-04-22 03:23
> Some background (see [onnx/onnx#401 (comment)](https://github.com/onnx/onnx/issues/401#issuecomment-356281852)):
> 
> What happens is that nobody ever _wants_ to use asymmetric padding, but sometimes it's impossible to have perfectly symmetric padding (I believe if the input and output sizes aren't either both even or both odd). And different frameworks have historically made different assumptions about _which asymmetry_ to choose when they're asked to pad symmetrically but can't make it perfectly symmetric. So ONNX has to represent these differences explicitly, which means we probably want to figure out what choice Flux/NNlib is implicitly making and also provide a means to bypass that choice and use explicitly provided asymmetries...

@jekbradbury Assymetric padding is also used in causal Conv1D. See [keras-tcn](https://github.com/philipperemy/keras-tcn).

**Comment by bhvieira** [comment] 2020-04-22 12:34
The issue is still Open over there as well: https://github.com/JuliaGPU/CuArrays.jl/issues/356, didn't see it before.
Some temporary solutions are proposed there.
