### ISSUE TITLE
dropout function is implemented as just an identity

### ISSUE THREAD

**Issue by AzamatB** [FluxML/Flux.jl#1084] opened 2020-03-14 10:59 UTC
The forward pass of the `Dropout` layer, which gets called when you do something like`d = Dropout(p); d(x)` is defined as just an identity function [here](https://github.com/FluxML/Flux.jl/blob/df3f904f7c34f095562693b6a9ca67047319dea0/src/layers/normalise.jl#L22).

Is that a bug? Or am I going crazy?

**Comment by dhairyagandhi96** [comment] 2020-03-14 11:09
It's because it is only supposed to do the dropout layer during training time, which is why the masking is implemented in the `adjoint` definition.

During test time, which is every time else, it's supposed to be off, ie an `identity`. It's a neat trick, not a bug.

**Comment by dhairyagandhi96** [comment] 2020-03-14 11:10
Closing this now, but do feel free to open if you find any discrepancy in the implementation.

**Comment by AzamatB** [comment] 2020-03-14 11:42
From Flux's [documentation](https://fluxml.ai/Flux.jl/stable/models/layers/#Flux.Dropout):
```Julia
help?> Dropout
search: Dropout AlphaDropout

  Dropout(p, dims = :)

  A Dropout layer. In the forward pass, applies the dropout function on the input.

  Does nothing to the input once testmode! is false.

help?> Flux.dropout
  dropout(p, dims = :)

  Dropout function. For each input, either sets that input to 0 (with probability p) or scales it by 1/(1-p).
The dims argument is to specify the unbroadcasted dimensions, i.e. dims=1 does dropout along columns and dims=2 along rows.
This is used as a regularisation, i.e. it reduces overfitting during training. 

  See also Dropout.
```
The documentation makes a clear distinction between `Dropout` as a layer, which depends on train/test mode and `dropout` as a function, which does not depend on train/test mode and does what it should do.
So I would call the current implementation a bug since it contradicts the documentation.
> It's because it is only supposed to do the dropout layer during training time

Please, note that there are works that apply dropout during _inference_ as well. Notably, one such example is [Tacotron 2](https://arxiv.org/abs/1712.05884), which currently is state-of-the-art for Text-to-Speech synthesis. This is how I actually encountered this bug: I was implementing Tacotron 2 and `dropout` function that I was calling in the forward pass of my custom layer was not doing what it supposed to do.

**Comment by AzamatB** [comment] 2020-03-14 11:44
Given the remarks above, I would request that you reopen this issue.

**Comment by CarloLucibello** [comment] 2020-03-14 12:36
yep, I think we should define the `dropout` function to always perform dropout. Or we can add a boolean `active` argument as an input.  

Then the `Dropout` layer will just perform identity if not active (in test phase), otherwise call `dropout`

**Comment by CarloLucibello** [comment] 2020-03-14 12:37
currently, the safe thing to do is to use the `Dropout` layer in combination with `testmode!(model)` and `trainmode!(model)`.

**Comment by AzamatB** [comment] 2020-03-14 12:53
> Currently, the safe thing to do is to use the `Dropout` layer in combination with `testmode!(model)` and `trainmode!(model)`.

In [Tacotron 2](https://arxiv.org/abs/1712.05884), there are some layers, which do dropout during training only as usual, and there are other layers, which always dropout including during inference time. So `Dropout` layer in combination with `testmode!` won't work. To work around this issue I had to pirate the `dropout` function:
```Julia
function Flux.dropout(x, p)
   q = 1 - p
   y = rand!(similar(x))
   y .= Flux._dropout_kernel.(y, p, q)
   x .* y
end

Flux.@adjoint function Flux.dropout(x, p)
   q = 1 - p
   y = rand!(similar(x))
   y .= Flux._dropout_kernel.(y, p, q)
   return x .* y, Δ -> (Δ .* y, nothing)
end
```
P.S.: I was not sure if my overridden `dropout` would still call the `adjoint` defined for it in Flux, so I pirated it as well.

**Comment by CarloLucibello** [comment] 2020-03-14 14:59
You can set train/test mode for specific layers:
```julia
c = Chain(Dense(10,10), Dropout(0.5), Dense(10,10))
testmode!(c)
trainmode!(c[2])
```
In any case, we should change `dropout` to you definition, would you submit a PR?

**Comment by jondeuce** [comment] 2020-03-20 19:35
> You can set train/test mode for specific layers:
> 
> ```julia
> c = Chain(Dense(10,10), Dropout(0.5), Dense(10,10), Dropout(0.5))
> testmode!(c)
> trainmode!(c[2])
> ```

This currently doesn't work btw @CarloLucibello (I was just bit by this bug):

```julia
c = Chain(Dense(10,10), Dropout(0.5), Dense(10,10), Dropout(0.5))
x = randn(10)

testmode!(c)
trainmode!(c[4]) # dropout at output only
a1 = Flux.activations(c, x)
a2 = Flux.activations(c, x)

a1[2] == a2[2] # true (expected)
a1[4] == a2[4] # true <-- expected false; dropout wasn't applied at the output layer
```

The issue is that while the `Dropout` layer is successfully set to active by `trainmode!`, this just makes it call `dropout` internally which right now is `identity` when outside a gradient call. The redefinition of `dropout` by @AzamatB above (w/ `dims` keyword added) fixes the issue:

```julia
function Flux.dropout(x, p; dims = :)
    q = 1 - p
    y = rand!(similar(x, Flux._dropout_shape(x, dims)))
    y .= Flux._dropout_kernel.(y, p, q)
    x .* y
end

Zygote.@adjoint function Flux.dropout(x, p; dims = :)
   q = 1 - p
   y = rand!(similar(x, Flux._dropout_shape(x, dims)))
   y .= Flux._dropout_kernel.(y, p, q)
   return x .* y, Δ -> (Δ .* y, nothing)
end
Zygote.refresh()
```

**Closed** 2020-07-09 13:11 UTC
