### ISSUE TITLE
Performance regression with graph neural networks 

### ISSUE THREAD

**Issue by DhairyaLGandhi** [FluxML/Flux.jl#1577] opened 2021-04-16 16:28 UTC
Some workloads seem to have regressed by as much as 40% in the latest tag compared to previous. The setup for this is a bit complex, but we have reproducible runs [here](https://github.com/aced-differentiate/flux12_tests) with the following results (note the last column which corresponds to train times)

# v0.11.6
num_pts,start_err,end_err,mae,train_time
20000,      2.699418,   0.0052020596,0.052836508,**933.3846**
20000,2.9156048,0.008110261,0.06857145,**1120.4064**
20000,2.942271,0.006664136,0.061609246,**994.0112**
# v0.12.1
num_pts,start_err,end_err,mae,train_time
20000,2.8409498,0.0062447544,0.05986253,**1416.244**
20000,2.526858,0.0050164107,0.051576257,**1612.1304**
20000,3.2492979,0.004473778,0.049020223,**1297.6096**

**Comment by darsnack** [comment] 2021-04-16 20:43
Is it possible to get the model architecture code? I can't find where the `Xie_model` used is defined.

Also, separate backwards and forwards pass measurements would be good.

**Comment by DhairyaLGandhi** [comment] 2021-04-17 09:29
That's in AtomGraphNets.jl

**Comment by darsnack** [comment] 2021-04-17 12:45
Thanks, but I can't find `Xie_model` defined in the source. Perhaps something didn't get pushed?

Looking at the paper, it looks like the model is convolutions, `Parallel`, dense, and pooling layers?

**Comment by DhairyaLGandhi** [comment] 2021-04-17 14:27
Use `build_cgcnn` instead

**Comment by darsnack** [comment] 2021-04-17 14:58
I think this might be related to changes to NNlib/Zygote. Looking at the model, the only Flux layer that I see is `Dense`. There was a performance regression on `Dense` prior to releasing v0.12, but we added the fast path back in. So, for `AbstractVecOrMat` input (which is used in the model here), `Dense` should be the exact same on v0.11.6 and v0.12.1. We'll have to measure the forward and backward pass separately to dig in some more.

Weren't there some recent changes to Zygote related to sparse matrices?

**Comment by DhairyaLGandhi** [comment] 2021-04-17 15:01
No there weren't, we haven't merged any iirc

**Comment by darsnack** [comment] 2021-04-17 15:03
Btw do you know if the original measurement runs both used Julia 1.6?

**Comment by rkurchin** [comment] 2021-04-28 20:37
Hi, popped in because I was curious about the status of this. The comparison I did that Dhairya pasted above was with 1.5. I'm about to launch a set with 1.6; will let you know what happens!

**Comment by rkurchin** [comment] 2021-04-30 14:51
Okay, here is is in Julia 1.6.0, Flux 0.12.3:
num_pts,start_err,end_err,mae,**train_time**
20000,3.2267997,0.006657221,0.060379118,**1584.4083**
20000,3.2261496,0.008941425,0.07608067,**1556.621**
20000,3.0106075,0.005385604,0.0545222,**1619.9683**
20000,1.4343624,0.015774088,0.097829245,**1601.0393**
20000,4.1569996,0.007203579,0.061540548,**1648.0889**
20000,2.3893049,0.009316431,0.07490431,**1550.8058**

And here it is in Julia 1.5.1, Flux 0.12.1 (ran again just as a sanity check, same columns as data above):
20000,3.1836119,0.0052007455,0.052357405,**1435.9447**
20000,2.9032593,0.0049671847,0.05111917,**1355.3989**
20000,2.9604344,0.006360177,0.060901433,**1453.6956**
20000,2.1187713,0.006271715,0.05874515,**1409.6694**
20000,3.1333485,0.025516426,0.13839585,**1451.6122**
20000,5.58184,0.010527108,0.083045706,**1428.3314**

**Comment by darsnack** [comment] 2021-04-30 15:25
I think the next thing we'll want to test is forward vs. backward pass. So a single forward pass through the network vs single forward+backward pass through the network.

From there we might try isolating the issue by layer type.

**Comment by ToucheSir** [comment] 2021-04-30 15:38
How well do the libraries involved play with profiling? Having a before and after flamegraph could also help.

**Comment by DhairyaLGandhi** [comment] 2021-04-30 16:08
Right, so the backwards pass in the fast paths might be of interest here.

**Comment by rkurchin** [comment] 2021-04-30 19:00
I've been meaning to do some more serious profiling on AtomicGraphNets but haven't really gotten around to it yet as the performance hasn't been bottlenecking anything. It's probably not going to be a priority for me in the near future to be totally honest, but it's all open-source and I'd certainly welcome other folks diving in, especially if it's useful to improve some Flux stuff! The test cases I've been running are basically identical to example 1 (which should hopefully work for you if you download the data using the script provided – you'll have to make a Materials Project API key first), though training on a lot more points obviously. See repo here: https://github.com/aced-differentiate/AtomicGraphNets.jl (note that it may be moving to a different org soon, I'll try to remember to drop a link here if that happens 😆 )

**Comment by CarloLucibello** [comment] 2023-02-05 14:36
closing since it needs some transparent benchmarks

**Closed by CarloLucibello** 2023-02-05 14:36 UTC
Labels: regression
