### ISSUE TITLE
Gradients of Chain including leakyrelu function

### ISSUE THREAD

**Issue by matsueushi** [FluxML/Flux.jl#963] opened 2019-12-09 06:14 UTC
I'm building a Chain model with `leakyrelu` function and working with `Float32` arrays (as in the performance tips in the documentation). However, `gradient` returns `Float64` numbers even if inputs and outputs are both `Float32`.

If I replace `leakyrelu` by `relu`, I can get `Float32` gradients as expected.
```
using Flux

x = rand(Float32, 2, 4)

@info "Case1"
m1 = Chain(Dense(2, 2), BatchNorm(2, relu))

@info typeof(m1(x))
@info typeof(sum(m1(x)))

grad1 = gradient(()->sum(m1(x)), params(m1))

for g in grad1.grads
    println(g)
end


@info "Case2"
m2 = Chain(Dense(2, 2), BatchNorm(2, leakyrelu))

@info typeof(m2(x))
@info typeof(sum(m2(x)))

grad2 = gradient(()->sum(m2(x)), params(m2))

for g in grad2.grads
    println(g)
end
```
gives

```shell
[ Info: Case1
[ Info: Array{Float32,2}
[ Info: Float32
Pair{Any,Any}(Base.RefValue{typeof(^)}(^), Base.RefValue{Any}((x = nothing,)))
Pair{Any,Any}(Float32[1.0, 1.0], Float32[1.8566748, 1.5298694])
Pair{Any,Any}(Float32[1.15647 -0.4924318; -0.7449282 -0.06118404], Float32[-0.33268705 -0.7818329; 0.0061671166 -0.079785615])
Pair{Any,Any}(Float32[0.0, 0.0], Float32[2.0, 1.0])
Pair{Any,Any}(Base.RefValue{Val{2}}(Val{2}()), Base.RefValue{Any}((x = nothing,)))
Pair{Any,Any}(BatchNorm(2, λ = relu), Base.RefValue{Any}((λ = nothing, β = Float32[2.0, 1.0], γ = Float32[1.8566748, 1.5298694], μ = nothing, σ² = nothing, ϵ = -27.19962f0, momentum = nothing)))
Pair{Any,Any}(Float32[0.0, 0.0], Float32[2.3841858e-7, -1.7881393e-7])
[ Info: Case2
[ Info: Array{Float32,2}
[ Info: Float32
Pair{Any,Any}(Float32[0.0, 0.0], [2.019999999552965, 2.019999999552965])
Pair{Any,Any}(BatchNorm(2, λ = leakyrelu), Base.RefValue{Any}((λ = nothing, β = [2.019999999552965, 2.019999999552965], γ = [1.7623343391225044, 1.6222754076805699], μ = nothing, σ² = nothing, ϵ = -25.9319391722397, momentum = nothing)))
Pair{Any,Any}(Base.RefValue{typeof(^)}(^), Base.RefValue{Any}((x = nothing,)))
Pair{Any,Any}(Float32[1.0, 1.0], [1.7623343391225044, 1.6222754076805699])
Pair{Any,Any}(Float32[0.0, 0.0], [-5.960464566356904e-8, -5.2154064067444494e-8])
Pair{Any,Any}(Base.RefValue{Val{2}}(Val{2}()), Base.RefValue{Any}((x = nothing,)))
Pair{Any,Any}(Float32[0.5769862 0.35130578; -0.46524963 1.0688603], [-0.28407584893631815 0.46736161226906603; 1.0983287075833459 0.4783004764828599])
```
How can I get the gradients of `leakyrelu` without typecasting from `Float64` to `Float32`?

**Comment by KristofferC** [comment] 2019-12-12 08:07
The problem is with the division operator in `leakyrelu` (https://github.com/FluxML/NNlib.jl/blob/30e61ef6233a32cea5005b8738fcd110ab7a363d/src/activation.jl#L54) which in the backwards pass turns into an `inv` call which gives `Float64`.

```jl
julia> leakyrelu'(Float32(2.0))
1.0
```

Doing a modification based on the same strategy as in https://github.com/FluxML/Flux.jl/pull/538:

```jl
julia> myleakyrelu(x::Real, a = oftype(x * 1//1, 0.01)) = max(a*x, x* 1//1)
leakyrelu (generic function with 2 methods)

julia> myleakyrelu'(Float32(2.0))
1.0f0
```

I'm not exactly sure why the `/1` is in the original function at all but you could try use this version of the activation function and see what happens.

**Comment by matsueushi** [comment] 2019-12-13 01:42
Thanks. The `//1` version of `leakyrelu` returns `Float32` gradients. I would use this one.

```julia
using Flux

myleakyrelu(x::Real, a = oftype(x * 1//1, 0.01)) = max(a*x, x* 1//1)

x = rand(Float32, 2, 4)
m1 = Chain(Dense(2, 2), x->myleakyrelu.(x))
grad1 = gradient(()->sum(m1(x)), params(m1))

for g in grad1.grads
    println(g)
end
```

```shell
Pair{Any,Any}(Float32[0.37646264 -0.4183135; -0.13610882 0.82453084], Float32[0.9372932 0.6876661; 1.7729647 2.019258])
Pair{Any,Any}(Float32[0.0, 0.0], Float32[1.03, 4.0])
```

I found `/1` was added by the commit https://github.com/FluxML/NNlib.jl/commit/8b7d90d75786175bbd3045fa57288ecddb443784#diff-73726c53a345943d6bc186d5562d8516R87.

**Comment by CarloLucibello** [comment] 2020-02-26 18:57
this has been fixed in https://github.com/FluxML/NNlib.jl/pull/149

**Closed by CarloLucibello** 2020-02-26 18:57 UTC
