### ISSUE TITLE
XOR Error not converging to 0

### ISSUE THREAD

**Issue by smitch151** [FluxML/Flux.jl#1352] opened 2020-10-12 21:24 UTC
Hi All,

I'm trying a very simple example, of XOR where if the two inputs are identical, the output is 1, and if the two inputs are different, the output is 0. When I try to train a NN to solve this, error is stalling at .25, and not reaching 0. What am I doing wrong? 

```
### Packages
using Flux, Statistics, Distributions
using Flux: @epochs

## Creating XOR Dataset
p = 0.5
N = 10000
d = Binomial(1,p)
A = rand(d,N)
B = rand(d,N)

train_x = hcat(A,B)
train_y = A .== B
train_y = convert(Array{Float32}, train_y)

### Creating model
model = Chain(Dense(2, 5, relu),
    Dense(5,10, relu),
    Dense(10,5, relu),
    Dense(5,1))

ps = Flux.params(model) #parameters of model

### Creating Loss
loss(x,y) = mean(abs2, model(x).-y)

evalcb = function()
    display(loss(train_x',train_y'))
end

evalcb()

### Training
opt = ADAM(1.0)
dataset = [(train_x', train_y')]  #train 100 times
Flux.@epochs 10 Flux.train!(loss, ps, dataset, opt, cb = evalcb)

opt = ADAM(0.1)
Flux.@epochs 500 Flux.train!(loss, ps, dataset, opt, cb = evalcb)

```
Thanks,

**Comment by Samyak2** [comment] 2020-10-13 10:04
I'm not sure about this but, I think it is related to the initialisation of parameters - certain values of parameters leads to the model converging to a local minima. I came to this conclusion by re-initialising and re-training the model a few times. The model converged to a low loss (order of 10^-5) a few times while it was stuck at 0.25 or 0.137 other times.

I can confirm that this issue gets solved by using a larger model (more parameters implies there will be a higher probability of finding params with desired values)
```julia
model = Chain(Dense(2, 10, relu),
    Dense(10, 20, relu),
    Dense(20, 10, relu),
    Dense(10, 1))
```
or by lowering the learning rate
```julia
opt = ADAM(0.01)
```
or both.

**Comment by DhairyaLGandhi** [comment] 2020-10-13 10:13
Closing this since it doesn't seem like a problem with the package itself. You probably do want a lower learning rate in this case. Feel free to reopen if you find an issue with any part of the package implementation. Thanks!

**Closed by DhairyaLGandhi** 2020-10-13 10:13 UTC
