### ISSUE TITLE
Params don't calculate for manual network

### ISSUE THREAD

**Issue by pmcvay** [FluxML/Flux.jl#487] opened 2018-11-11 20:46 UTC
I'm new to flux - but I can't get the basic example shown on the README to work correctly. It seems to suggest that
```julia
model = Dense(2,10, σ)
```
is equivalent to 
```julia
W = param(randn(2, 10))
b = param(randn(2))
model2(x) = σ.(W * x .+ b)
```

However, the output of `params` is correct for the first way and empty for the second way
```julia
julia> params(model)
2-element Array{Any,1}:
 Flux.Tracker.TrackedReal{Float64}[-0.133968 (tracked) -0.674479 (tracked); 0.193659 (tracked) 0.444847 (tracked); … ; -0.668676 (tracked) -0.387189 (tracked); 0.683113 (tracked) 0.235091 (tracked)]
 Flux.Tracker.TrackedReal{Float64}[0.0 (tracked), 0.0 (tracked), 0.0 (tracked), 0.0 (tracked), 0.0 (tracked), 0.0 (tracked), 0.0 (tracked), 0.0 (tracked), 0.0 (tracked), 0.0 (tracked)]          
```

```julia
julia> params(model2)
0-element Array{Any,1}
```

**Comment by MikeInnes** [comment] 2018-11-14 13:42
Yes, we can't pull the parameters out of an arbitrary function, you'd have to make a custom layer for that as @CarpeNecopinum points out.

In this case, you can also just work directly on the list `[W, b]` since you have those parameters right there; `params` is just a convenience for doing that.

**Comment by dhairyagandhi96** [comment] 2018-11-19 17:18
We assume that the issue is resolved, but feel free to report any new information regarding this or any further issues. They are always welcome. Closing this for now.
Thanks all.

**Closed by dhairyagandhi96** 2018-11-19 17:18 UTC
